name: namer_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  regexed_validator: ^2.0.0+1
  amap_map: ^1.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/json/data.json
    - lib/image/iot0102.jpg
    - lib/image/java-250220.jpg
    - lib/image/jichuban-20252.jpg
    - lib/image/map.png
    - lib/image/device/AED.jpg
    - lib/image/device/danjia.jpg
    - lib/image/device/miehuoqi.png
    - lib/image/device/firstaid.png
    - lib/image/device/lunyi.jpg
    - lib/image/device/sos.jpg
